<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ZytechBoost</AssemblyName>
    <RootNamespace>ZytechBoost</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>Zytech</Authors>
    <Description>Zytech Boost - Optimización de sistema para Windows</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="app.manifest" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.*" />
    <Resource Include="Styles\*.xaml" />
    <EmbeddedResource Include="Scripts\*.ps1" />
  </ItemGroup>

</Project>
